### ISSUE TITLE
vertical alignment CSS not working on Firefox/Linux

### ISSUE THREAD

**Issue by Debenben** [mathjax/mathjax-v3#123] opened 2018-05-20 20:50 UTC
Using the current demo https://mathjax.github.io/mj3-demos/mj3-tex2html-global.html with Firefox/Linux the input `\displaystyle\sum (1)\textstyle\sum (1)\scriptstyle\sum (1)\scriptscriptstyle\sum (1)` looks like

![screenshot from 2018-05-20 22-43-52](https://user-images.githubusercontent.com/35615783/40283498-553c75b0-5c7f-11e8-9f47-4b27bf906e7c.png)

where the bottom edges of brackets, numbers and operators are aligned, instead of 
![screenshot from 2018-05-20 22-43-30](https://user-images.githubusercontent.com/35615783/40283501-5da3602e-5c7f-11e8-8581-dd245cb3516f.png)
(LaTeX) or 
![screenshot from 2018-05-20 22-45-02](https://user-images.githubusercontent.com/35615783/40283510-787387c6-5c7f-11e8-8ab1-f5ac59132b21.png)
(math.stackexchange)

**Comment by dpvc** [comment] 2018-05-24 03:51
I am not able to reproduce your result in Firefox on Mac OS.  On the other hand, if I disable one of the CSS rules, I do get your result, so I'm wondering if that rule isn't triggering properly for you.

Can you open the developer console and inspect one of the parentheses, and see if you see the highlighted rule below:

<img width="1127" alt="mjv3" src="https://user-images.githubusercontent.com/432782/40463574-d522b526-5eca-11e8-9e3b-40fe0c1818e6.png">

(the one for `mix-symmetric > mjx-c`)?  If I disable this rule, I see the same result that you see.

**Comment by Debenben** [comment] 2018-05-24 12:07
I think the rule is there:

![screenshot from 2018-05-24 14-03-32](https://user-images.githubusercontent.com/35615783/40484332-80b67158-5f5b-11e8-96f2-d6645fc97a33.png)

If I disable the rule, it does not change anything.

**Comment by Debenben** [comment] 2018-05-24 13:33
vertical-align: top

![screenshot from 2018-05-24 15-30-35](https://user-images.githubusercontent.com/35615783/40488706-b08a6dba-5f67-11e8-9eb9-f11e60b4d79c.png)

vertical-align: 1em

![screenshot from 2018-05-24 15-31-17](https://user-images.githubusercontent.com/35615783/40488734-bd375b22-5f67-11e8-8821-c640df99bdcd.png)

vertical-align: bottom

![screenshot from 2018-05-24 15-32-16](https://user-images.githubusercontent.com/35615783/40488747-c4f150ac-5f67-11e8-9427-8f9894837574.png)

**Comment by dpvc** [comment] 2018-05-24 13:47
OK, that is helpful.  Can you try this?  Select the `mjx-symmetric` element surrounding one of the parentheses, and add `display: inline-block` to the rule for that element:

<img width="1124" alt="mj3-align1" src="https://user-images.githubusercontent.com/432782/40489459-03a36e6a-5f1e-11e8-90e3-e00bc1113a26.png">

Then select all the `mjx-mstyle` elements (one at a time) and add `display: inline-block` as element properties:

<img width="1124" alt="mj3-align2" src="https://user-images.githubusercontent.com/432782/40489584-489a5e34-5f1e-11e8-8dd6-d1f5b9cd7923.png">

You'll have to do it individually, since there is no CSS rule for `mjx-mstyle` currently that would let you do it for all at once.

See if doing that resolves the issue (fingers crossed).

**Comment by Debenben** [comment] 2018-05-24 14:01
I think that is the issue. I was able to apply it to the first bracket:

![screenshot from 2018-05-24 15-56-27](https://user-images.githubusercontent.com/35615783/40490140-2b6d743e-5f6b-11e8-843e-5747b880b249.png)

Maybe I am just too stupid to apply it to the others, but it seemed like the display: inline-block got inherited from the first one, so it was already shown in the console with the green marking and I couldn't add it again.

**Comment by dpvc** [comment] 2018-05-24 14:44
OK, I've pushed a [modified version](https://rawgit.com/dpvc/mj3-demos/valign-test/mj3-tex2html-global.html) for testing that includes the `display: inline-block` settings.  Put your example into that and see if it works properly.

**Comment by Debenben** [comment] 2018-05-24 14:51
No, that doesn't work. It ist the same as the unmodified version. 

![screenshot from 2018-05-24 16-48-00](https://user-images.githubusercontent.com/35615783/40493199-78eee600-5f72-11e8-8978-7b304590b587.png)

For the screenshot I uploaded earlier, I might have added some display: inline-block property falsely to some other element as well.

**Comment by dpvc** [comment] 2018-05-24 15:07
OK thanks.  I'll have to think of something else.  What flavor of linux are you using, and what version of Firefox?

**Comment by Debenben** [comment] 2018-05-24 15:10
debian stretch with firefox version 52.8.0

**Comment by zorkow** [comment] 2018-05-24 16:11
I can reproduce that issue on Firefox/Linux v58.2.0 and v61.0b7 (aurora channel).

**Comment by zorkow** [comment] 2018-05-24 16:39
I tried MacOS, Firefox v61.0beta and could _not_ reproduce the problem.

However, on ChromeOS, Firefox v60.0.1 I can see the same issue. So it is probably a Linux problem.

**Comment by davidlowryduda** [comment] 2018-05-24 17:30
Do you mean that you *could not* reproduce the same issue on Windows?

**Comment by dpvc** [comment] 2018-05-25 13:04
I am also able to reproduce on windows.  So it looks like Mac OS is the outlier.  I will have to rethink how this is being handled.   Rats!

**Comment by dpvc** [comment] 2018-10-06 15:47
This has been merged into the master branch.

**Closed** 2018-10-06 15:47 UTC
Labels: bug, fixed
