### ISSUE TITLE
mfenced not working?

### ISSUE THREAD

**Issue by stnor** [mathjax/mathjax-v3#86] opened 2018-03-14 11:43 UTC
This mathml:
```
	<math><mi>t</mi><mo>·</mo><mfenced open="(" close=")"><mrow><mn>2</mn><mo>+</mo><mn>2</mn></mrow></mfenced><mo>=</mo><mn>3</mn><mo>·</mo><mn>3</mn><mo>+</mo><mn>3</mn></math>
```
renders as "t * (2 + 2) = 3 * 3 + t" with MathJAX 2.17.

With mathjax-v3 it renders without the parentheses (npm, alpha 3) and same when using your live demo page mj3-mml2html.html (local copy).

Please help.

/Stefan

**Comment by dpvc** [comment] 2018-03-14 11:51
The mfenced element is not yet implements in the v3 CommonHTML output, so this is currently the expected behavior.  There are a number of elements that need to be implemented (e.g., menclose, maction, mfenced), as well as some features of elements that are otherwise implemented (e.g., mfrac's beveled and linethickness attributes).

This is still a work in progress.

**Comment by stnor** [comment] 2018-03-14 11:58
Thanks for the quick response.
I understand that this is still early days, but I have a fairly simple use-case for our math site (k-9) built using es6 and webpack.

As v2 doesn't support modules I'm betting on v3, and would love to get mfenced working. Is there anything I can do to help (testing, contributions or otherwise) or to work around this?

Thanks!

**Comment by dpvc** [comment] 2018-03-14 13:06
Here is a work-around for now.  This installs a MathML pre-filter on the MathML input jax that looks for `mfenced` elements and replaces them with equivalent `mrow` elements with internal `mo` elements. 

```
import {MathML} from "mathjax3/input/mathml.js";
import {HTMLNodes} from "mathjax3/util/HTMLNodes.js";
const NODES = new HTMLNodes();
const myMathML = new MathML();
myMathML.mmlFilters.add((math) => {
    const mml = math.data.getElementsByTagName('mfenced');
    for (const mfenced of mml) {
        NODES.document = mfenced.ownerDocument;
        const open  = (mfenced.hasAttribute('open') ? mfenced.getAttribute('open') : '(');
        const close = (mfenced.hasAttribute('close') ? mfenced.getAttribute('close') : ')');
        const sep   = (mfenced.hasAttribute('separators') ? mfenced.getAttribute('separators') : '+').split('');
        const mrow  = NODES.node('mrow');
        if (open) {
            mrow.appendChild(NODES.node('mo', {}, [NODES.text(open)]));
        }
        let c = '';
        for (const child of Array.from(mfenced.childNodes)) {
            if (c) {
                mrow.appendChild(NODES.node('mo', {}, [NODES.text(c)]));
            }
            mrow.appendChild(child);
            c = sep.shift() || c;
        }
        if (close) {
            mrow.appendChild(NODES.node('mo', {}, [NODES.text(close)]));
        }
        mfenced.parentNode.replaceChild(mrow, mfenced);
    }
});
```

Then pass `myMathML` as the `InputJax` in the options to your `MathJax.document()` call. That should work for you for now until the `mfenced` element is implemented natively.

Note, however, that the next alpha version will include a breaking change with the current alpha.  There will be a new library that mediates the handling of HTML elements, and the filter will need to use that instead of the older `HTMLNodes` library that is used here.  In the future, the filter will have to look like

```
myMathML.mmlFilters.add((math) => {
    const mml = math.data.getElementsByTagName('mfenced');
    const adaptor = MML.adaptor;
    for (const mfenced of mml) {
        const open  = (adaptor.hasAttribute(mfenced, 'open') ? adaptor.getAttribute(mfenced, 'open') : '(');
        const close = (adaptor.hasAttribute(mfenced, 'close') ? adaptor.getAttribute(mfenced, 'close') : ')');
        const sep   = (adaptor.hasAttribute(mfenced, 'separators') ? adaptor.getAttribute(mfenced, 'separators') : '+').split('');
        const mrow  = adaptor.node('mrow');
        if (open) {
            adaptor.append(mrow, adaptor.node('mo', {}, [adaptor.text(open)]));
        }
        let c = '';
        for (const child of adaptor.childNodes(mfenced)) {
            if (c) {
                adaptor.append(mrow, adaptor.node('mo', {}, [adaptor.text(c)]));
            }
            adaptor.append(mrow, child);
            c = sep.shift() || c;
        }
        if (close) {
            adaptor.append(mrow, adaptor.node('mo', {}, [adaptor.text(close)]));
        }
        adaptor.replace(mrow, mfenced);
    }
});
```

**Comment by stnor** [comment] 2018-03-14 13:15
Thanks Davide! 🥇 
I'll give that a try, and let you know how it goes.

Any ideas on when "mfenced" will be implemented. Weeks, months, before summer, 2018? :)

**Comment by dpvc** [comment] 2018-03-14 13:24
The current plan is to finish up the missing features and tags in the CommonHTML output next.  So that should be coming along in the near future.

**Comment by stnor** [comment] 2018-03-14 13:45
Thanks, workaround works like a charm. 👍 👍 👍
As a token of my appreciation I donated $500 to your project.

Thanks again,
Stefan

**Comment by dpvc** [comment] 2018-03-14 15:14
Your support is much appreciated!

I'm glad the patch worked for you.  Of course, when `mfenced` is implemented, this can be removed (though it will still work, even then).

**Comment by stnor** [comment] 2018-03-21 13:16
It seems like the workaround will only replace the first occurrence of mfenced. Any ideas?

**Comment by stnor** [comment] 2018-03-21 13:24
This hack works, let me know if you have something better :)
````
    mathML.mmlFilters.add((math) => {
      const mml = math.data.getElementsByTagName('mfenced')
      let numberOfGroups = mml.length;
      for (var i=0; i<numberOfGroups; i++) {
        let mfenced = math.data.getElementsByTagName('mfenced')[0];
        console.log('looping', mfenced)
        NODES.document = mfenced.ownerDocument;
        const open = (mfenced.hasAttribute('open') ? mfenced.getAttribute('open') : '(');
        const close = (mfenced.hasAttribute('close') ? mfenced.getAttribute('close') : ')');
        const sep = (mfenced.hasAttribute('separators') ? mfenced.getAttribute('separators') : '+').split('');
        const mrow = NODES.node('mrow');
        if (open) {
          mrow.appendChild(NODES.node('mo', {}, [NODES.text(open)]));
        }
        let c = '';
        for (const child of Array.from(mfenced.childNodes)) {
          if (c) {
            mrow.appendChild(NODES.node('mo', {}, [NODES.text(c)]));
          }
          mrow.appendChild(child);
          c = sep.shift() || c;
        }
        if (close) {
          mrow.appendChild(NODES.node('mo', {}, [NODES.text(close)]));
        }
        mfenced.parentNode.replaceChild(mrow, mfenced);
      }
    });
  }
````

**Comment by dpvc** [comment] 2018-03-21 13:43
Ok, the problem is that the `mml` variable is an `HTMLCollection`, and that is a live list, so when the mfenced is replaced, the list changes.  We want to convert that to an array (that is not live).  That can be done by putting `Array.from()` around the value for `mml`.  I have changed my code above to do that, but the key change is

```
  const mml = Array.from(math.data.getElementsByTagName('mfenced'));
```

The rest should be able to stay the same.

**Comment by dpvc** [comment] 2018-06-06 20:19
The `mfenced` support has been merged to master.

**Closed** 2018-06-06 20:19 UTC
Labels: fixed

**Comment by stnor** [comment] 2018-09-09 12:33
I tried to upgrade to beta 1, but mfenced seems broken there still?
